#!/bin/bash

if [ -d ../../output/linux ]; then
    rm -rf ../../output/linux/*
fi

mkdir -p ../../output/linux

echo "Building snake game ..."
    g++ -O0 -Wall -std=c++17 -rdynamic -fPIC -c -g -ggdb -I../../main/headers ../../snake/snake.cpp -o ../../output/linux/snake.o
    g++ -shared -o ../../output/linux/snake.so ../../output/linux/snake.o
    rm ../../output/linux/snake.o
echo "Done"

echo "Building tictactoe game ..."
    g++ -O0 -Wall -std=c++17 -rdynamic -fPIC -c -g -ggdb -I../../main/headers ../../tictactoe/tictactoe.cpp -o ../../output/linux/tictactoe.o
    g++ -shared -o ../../output/linux/tictactoe.so ../../output/linux/tictactoe.o
    rm ../../output/linux/tictactoe.o
echo "Done"

echo "Building the executable ..."
    g++ -O0 -Wall -std=c++17 -rdynamic -g -ggdb -I../../main/headers ../../main/linux/main.cpp ../../main/linux/linux.cpp -o ../../output/linux/MiniGames.a -ldl
echo "Done"